package com.medibot.healthcare_platform.modules.triage.service;

import com.medibot.healthcare_platform.modules.identity.entity.User;
import com.medibot.healthcare_platform.modules.identity.repository.UserRepository;
import com.medibot.healthcare_platform.modules.triage.entity.TriageHistory;
import com.medibot.healthcare_platform.modules.triage.repository.TriageHistoryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
public class TriageHistoryService {

    private final TriageHistoryRepository triageRepository;
    private final UserRepository userRepository;

    /**
     * Persists the AI Triage chat result to the database for the patient's timeline.
     * * @param patientId ID of the logged-in patient
     * @param disease   The primary predicted disease from ML model
     * @param confidence The confidence score from the ML model
     * @param symptoms   The raw symptom string input by the user
     * @param tips       The list of preventive advice generated by Gemini
     */
    @Transactional
    public void saveTriageResult(UUID patientId, String disease, double confidence, String symptoms, List<String> tips) {
        log.info("Saving Triage History for patient: {} - Predicted: {}", patientId, disease);

        User patient = userRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient record not found."));

        // Format the tips list into a clean, readable string for storage
        String formattedAdvice = String.join("\n• ", tips);
        if (!tips.isEmpty()) {
            formattedAdvice = "AI Recommended Tips:\n• " + formattedAdvice;
        }

        TriageHistory history = TriageHistory.builder()
                .patient(patient)
                .predictedDisease(disease)
                .confidence(confidence)
                .symptomsInput(symptoms)
                .aiAdvice(formattedAdvice)
                .build();

        triageRepository.save(history);
    }

    /**
     * Retrieves the chronological triage history for a specific patient.
     */
    public List<TriageHistory> getHistoryByPatient(UUID patientId) {
        return triageRepository.findByPatientIdOrderByCreatedAtDesc(patientId);
    }

    /**
     * Deletes a specific triage entry from the timeline.
     */
    @Transactional
    public void deleteEntry(UUID historyId) {
        triageRepository.deleteById(historyId);
    }
}